###########
# SSH Keys
###########
key_name: my-gpu-key  # Name of the key pair to create
key_path: ~/.ssh/aws-gpu-key.pem  # Local path where the private key will be stored

###########
# IAM image
###########

s3_bucket_prefix: "my-rhel-ai-bucket"
iam_role_name: vmimport
raw_ami_object_name: "nvidia-bootc.ami"
ami_name: "rhel-ai"
raw_image_download_location: "../disk.raw"
ami_display_name: "RHEL AI 1.2"

volume_size: 1000              # EBS volume size (adjust as per your needs)
device_name: /dev/sda1

###########
# EC2 Instance
###########
vpc_cidr: "10.1.0.0/16"        # CIDR for VPC
subnet_cidr: "10.1.1.0/24"     # CIDR for subnet
availability_zone: eu-west-1a  # Choose an availability zone in eu-west-1
region: eu-west-1              # Your preferred AWS region
# https://aws.amazon.com/ec2/instance-types/
# https://aws.amazon.com/ec2/pricing/on-demand/
instance_type: g5.2xlarge      # Choose an instance type with GPU (1.35€/h)
# ami_id: ami-07d4917b6f95f5c2a  # RHEL 9 AMI for the eu-west-1 region

###########
# Component names
###########
vpc_name: my-gpu-vpc
subnet_name: my-gpu-subnet
security_group_name: my-gpu-sg
igw_name: my-gpu-igw
rtb_name: my-gpu-rtb
instance_name: gpu-rhel
